import clusters

blog,words,data=clusters.readfile('blogdata.txt') 
kclust=clusters.kcluster(data,k=20)
print([blog[item] for item in kclust[0]])
print([blog[item] for item in kclust[1]])
print([blog[item] for item in kclust[2]])
print([blog[item] for item in kclust[3]])
print([blog[item] for item in kclust[4]])
print([blog[item] for item in kclust[5]])
print([blog[item] for item in kclust[6]])
print([blog[item] for item in kclust[7]])
print([blog[item] for item in kclust[8]])
print([blog[item] for item in kclust[9]])
print([blog[item] for item in kclust[10]])
print([blog[item] for item in kclust[11]])
print([blog[item] for item in kclust[12]])
print([blog[item] for item in kclust[13]])
print([blog[item] for item in kclust[14]])
print([blog[item] for item in kclust[15]])
print([blog[item] for item in kclust[16]])
print([blog[item] for item in kclust[17]])
print([blog[item] for item in kclust[18]])
print([blog[item] for item in kclust[19]])